### ISSUE TITLE
Help text formatting is inconsistent

### ISSUE THREAD

**Issue by henesy** [pnd-tech-club/kazoo-quest#2]
"-help" is indented less than the other list items.

> help
> -help (Shows this screen)
>  -look (Shows you your surroundings)
>  -heal (Heals you but draws monsters nearby)
>  -use (Uses an item or object)
>  -take (Takes an item)
>  -n, s, e, w, u, d (Moves you in its respective direction)
>  -clear (Clears the screen)
>  -info (Shows your your stats)

**Comment by YeahImRose** [comment]
Fixed
