### ISSUE TITLE
Movement doesn't display text

### ISSUE THREAD

**Issue by henesy** [pnd-tech-club/kazoo-quest#3]
Moving "n" then "s" from origin will result in the "s" movement's description text not printing.

**Comment by henesy** [comment]
Moving any direction but north does not seem to print text upon movement:

> n
> You start walking to the north yet find that the mysterious light is dimming rapidly.  You decide to turn back until you find a light source.
> s
> s
> s
> w
> e
> 
> You have found yourself in a dimly lit cave.  You have no memory of how you got here or who you are.  There is a path to the north and south.  You see a torch on the ground.

**Comment by YeahImRose** [comment]
There is no room there currently
